// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-eJ6VlCsrDSYY9tqOOjX56TpI8sM8jA0',
    appId: '1:493430618844:web:b2598f5a94390e8c879219',
    messagingSenderId: '493430618844',
    projectId: 'friends-madeby-cp',
    authDomain: 'friends-madeby-cp.firebaseapp.com',
    storageBucket: 'friends-madeby-cp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5BYygYsEMmmheS_Ds76BlM7-mYHoan-o',
    appId: '1:493430618844:android:5d7c8c4d5409a8bb879219',
    messagingSenderId: '493430618844',
    projectId: 'friends-madeby-cp',
    storageBucket: 'friends-madeby-cp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3227nyYNp3niuPYtEAa9APZk3D51FpDU',
    appId: '1:493430618844:ios:e8fd524ea6ffac87879219',
    messagingSenderId: '493430618844',
    projectId: 'friends-madeby-cp',
    storageBucket: 'friends-madeby-cp.appspot.com',
    iosClientId: '493430618844-s1c3k12361vnhd2kj8p86tnho4cv91l0.apps.googleusercontent.com',
    iosBundleId: 'com.crescent.friends2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3227nyYNp3niuPYtEAa9APZk3D51FpDU',
    appId: '1:493430618844:ios:dcb367926cbfe919879219',
    messagingSenderId: '493430618844',
    projectId: 'friends-madeby-cp',
    storageBucket: 'friends-madeby-cp.appspot.com',
    iosClientId: '493430618844-b2oebvu6eckmlc6463p74hn9ovfo6rso.apps.googleusercontent.com',
    iosBundleId: 'com.crescent.friends2.RunnerTests',
  );
}
